** HEADER -----------------------------------------------------
**  DO-FILE METADATA
    //  algorithm name          5d_prep match mort 2021.do
    //  project:                BNR
    //  analysts:               Jacqueline CAMPBELL
    //  date first created      30-JUN-2022
    //  date last modified	  21-JUL-2022
    //  algorithm task          Prep, format and combine 2021 death data with 2015-2020 death dataset
    //  status                  Completed
    //  objective               To have one dataset with cleaned 2015-2021 death data for matching with cancer incidence dataset.
    
    ** General algorithm set-up
    version 17.0
    clear all
    macro drop _all
    set more off

    ** Initialising the STATA log and allow automatic page scrolling
    capture {
            program drop _all
    	drop _all
    	log close
    	}

    ** Set working directories: this is for DATASET and LOGFILE import and export
    ** DATASETS to encrypted SharePoint folder
    local datapath "X:/The University of the West Indies/DataGroup - repo_data/data_p117"
    ** LOGFILES to unencrypted OneDrive folder (.gitignore set to IGNORE log files on PUSH to GitHub)
    local logpath X:/OneDrive - The University of the West Indies/repo_datagroup/repo_p117

    ** Close any open log file and open a new log file
    capture log close
    log using "`logpath'\5d_prep match mort 2021.smcl", replace
** HEADER -----------------------------------------------------

**************************************
**     Prep 2021 death variables    **
** for matching with cancer dataset **
**************************************
***************
** DATA IMPORT  
***************
** LOAD the cleaned national registry 2021 Stata death dataset that was imported into multi-year REDCap database
** This dataset was created during the cleaning of 2021 data in p141/v07
//use "X:\The University of the West Indies\DataGroup - repo_data\data_p141\version07\3-output\2021_deaths_cleaned_cancer" , clear
** Excel data generated using the REDCap report in multi-yr death db (BNRDeathData20082021) called 'cancer matching 2021 deaths'.

** JC 30jun2022: decided not to use the dataset prepared in p141 as this would not have the record_id from the multi-year database so will import and prep based on multi-year death db

** LOAD the national registry deaths 2021 excel dataset
import excel using "`datapath'\version09\1-input\BNRDeathData20082021-CancerMatching2021De_DATA_2022-07-21_1409_excel.xlsx" , firstrow case(lower)

count //3133; 3136; 3142; 3143; 3145 - note: there are 3 cases from 2020 that were collected after 2020 was cleaned


*******************
** DATA FORMATTING  
*******************
** PREPARE each variable according to the format and order in which they appear in DeathData REDCap database

************************
**  DEATH CERTIFICATE **
**        FORM        **
************************

** (1) record_id (auto-generated by REDCap)
label var record_id "DeathID"

** (2) redcap_event_name (auto-generated by REDCap)
gen event=.
replace event=1 if redcap_event_name=="death_data_collect_arm_1"
replace event=2 if redcap_event_name=="tracking_arm_2"

label var event "Redcap Event Name"
label define event_lab 1 "DC arm 1" 2 "TF arm 2", modify
label values event event_lab

** (3) dddoa: Y-M-D H:M, readonly
gen double dddoa2 = clock(dddoa, "YMDhm")
format dddoa2 %tcCCYY-NN-DD_HH:MM
drop dddoa
rename dddoa2 dddoa
label var dddoa "ABS DateTime"

** (4) ddda
label var ddda "ABS DA"
label define ddda_lab 4 "KG" 13 "KWG" 14 "TH" 20 "NR" 25 "AH" 98 "intern", modify
label values ddda ddda_lab

** (5) odda
if odda==. tostring odda ,replace
replace odda="" if odda=="."
label var odda "ABS Other DA"

** (6) certtype: 1=MEDICAL 2=POST MORTEM 3=CORONER 99=ND, required
label var certtype "Certificate Type"
label define certtype_lab 1 "Medical" 2 "Post Mortem" 3 "Coroner" 99 "ND", modify
label values certtype certtype_lab

** (7) regnum: integer, if missing=9999
label var regnum "Registry Dept #"

** (8) district: 1=A 2=B 3=C 4=D 5=E 6=F
/* Districts are assigned based on death parish
	District A - anything below top rock christ church and st. michael 
	District B - anything above top rock christ church and st. george
	District C - st. philip and st. john
	District D - st. thomas
	District E - st. james, st. peter, st. lucy
	District F - st. joseph, st. andrew
*/
label var district "District"
label define district_lab 1 "A" 2 "B" 3 "C" 4 "D" 5 "E" 6 "F", modify
label values district district_lab

** (9) pname: Text, if missing=99
label var pname "Deceased's Name"
replace pname = rtrim(ltrim(itrim(pname))) //5 changes

** (10) address: Text, if missing=99
label var address "Deceased's Address"
replace address = rtrim(ltrim(itrim(address))) //20 changes

** (11) parish
label var parish "Deceased's Parish"
label define parish_lab 1 "Christ Church" 2 "St. Andrew" 3 "St. George" 4 "St. James" 5 "St. John" 6 "St. Joseph" ///
						7 "St. Lucy" 8 "St. Michael" 9 "St. Peter" 10 "St. Philip" 11 "St. Thomas" 99 "ND", modify
label values parish parish_lab

** (12) sex:	1=Male 2=Female 99=ND
label var sex "Sex"
label define sex_lab 1 "Male" 2 "Female" 99 "ND", modify
label values sex sex_lab

** (13) age: Integer - min=0, max=999
label var age "Age"

** (14) agetxt
label var agetxt "Age Qualifier"
label define agetxt_lab 1 "Minutes" 2 "Hours" 3 "Days" 4 "Weeks" 5 "Months" 6 "Years" 99 "ND", modify
label values agetxt agetxt_lab

** (15) nrnnd: 1=Yes 2=No
label define nrnnd_lab 1 "Yes" 2 "No", modify
label values nrnnd nrnnd_lab
label var nrnnd "Is National ID # documented?"

** (16) nrn: dob-####, partial missing=dob-9999, if missing=.
label var nrn "National ID #"
format nrn %15.0g

** (17) mstatus: 1=Single 2=Married 3=Separated/Divorced 4=Widowed/Widow/Widower 99=ND
label var mstatus "Marital Status"
label define mstatus_lab 1 "Single" 2 "Married" 3 "Separated/Divorced" 4 "Widowed/Widow/Widower" 99 "ND", modify
label values mstatus mstatus_lab

** (18) occu: Text, if missing=99
label var occu "Occupation"

** (19) durationnum: Integer - min=0, max=99, if missing=99
label var durationnum "Duration of Illness"

** (20) durationtxt
label var durationtxt "Duration Qualifier"
label define durationtxt_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values durationtxt durationtxt_lab

** (21) dod: Y-M-D
format dod %tdCCYY-NN-DD
label var dod "Date of Death"

** (22) dodyear (not included in single year Redcap db but done for multi-year Redcap db)
drop dodyear
gen int dodyear=year(dod)
label var dodyear "Year of Death"

** (23) cod1a: Text, if missing=99
label var cod1a "COD 1a"

** (24) onsetnumcod1a: Integer - min=0, max=99, if missing=99
label var onsetnumcod1a "Onset Death Interval-COD 1a"

** (25) onsettxtcod1a: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod1a "Onset Qualifier-COD 1a"
label define onsettxtcod1a_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod1a onsettxtcod1a_lab

** (26) cod1b: Text, if missing=99
label var cod1b "COD 1b"

** (27) onsetnumcod1b: Integer - min=0, max=99, if missing=99
label var onsetnumcod1b "Onset Death Interval-COD 1b"

** (28) onsettxtcod1b: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod1b "Onset Qualifier-COD 1b"
label define onsettxtcod1b_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod1b onsettxtcod1b_lab

** (29) cod1c: Text, if missing=99
label var cod1c "COD 1c"

** (30) onsetnumcod1c: Integer - min=0, max=99, if missing=99
label var onsetnumcod1c "Onset Death Interval-COD 1c"

** (31) onsettxtcod1c: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod1c "Onset Qualifier-COD 1c"
label define onsettxtcod1c_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod1c onsettxtcod1c_lab

** (32) cod1d: Text, if missing=99
label var cod1d "COD 1d"

** (33) onsetnumcod1d: Integer - min=0, max=99, if missing=99
label var onsetnumcod1d "Onset Death Interval-COD 1d"

** (34) onsettxtcod1d: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod1d "Onset Qualifier-COD 1d"
label define onsettxtcod1d_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod1d onsettxtcod1d_lab

** (35) cod2a: Text, if missing=99
label var cod2a "COD 2a"

** (36) onsetnumcod2a: Integer - min=0, max=99, if missing=99
label var onsetnumcod2a "Onset Death Interval-COD 2a"

** (37) onsettxtcod2a: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod2a "Onset Qualifier-COD 2a"
label define onsettxtcod2a_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod2a onsettxtcod2a_lab

** (38) cod2b: Text, if missing=99
label var cod2b "COD 2b"

** (39) onsetnumcod2b: Integer - min=0, max=99, if missing=99
label var onsetnumcod2b "Onset Death Interval-COD 2b"

** (40) onsettxtcod2b: 1=DAYS 2=WEEKS 3=MONTHS 4=YEARS
label var onsettxtcod2b "Onset Qualifier-COD 2b"
label define onsettxtcod2b_lab 1 "Days" 2 "Weeks" 3 "Months" 4 "Years" 99 "ND", modify
label values onsettxtcod2b onsettxtcod2b_lab

** (41) pod: Text, if missing=99
label var pod "Place of Death"

** (42) deathparish
label var deathparish "Death Parish"
label define deathparish_lab 1 "Christ Church" 2 "St. Andrew" 3 "St. George" 4 "St. James" 5 "St. John" 6 "St. Joseph" ///
						7 "St. Lucy" 8 "St. Michael" 9 "St. Peter" 10 "St. Philip" 11 "St. Thomas" 99 "ND", modify
label values deathparish deathparish_lab

** (43) regdate: Y-M-D
label var regdate "Date of Registration"
format regdate %tdCCYY-NN-DD

** (44) certifier: Text, if missing=99
label var certifier "Name of Certifier"

** (45) certifieraddr: Text, if missing=99
label var certifieraddr "Address of Certifier"

** (46) namematch: readonly
label var namematch "Name Match"
label define namematch_lab 1 "names match but different person" 2 "no name match", modify
label values namematch namematch_lab

** (47) death_certificate_complete (auto-generated by REDCap): 0=Incomplete 1=Unverified 2=Complete
rename death_certificate_complete recstatdc
label var recstatdc "Record Status-DC Form"
label define recstatdc_lab 0 "Incomplete" 1 "Unverified" 2 "Complete", modify
label values recstatdc recstatdc_lab

*****************
**  Formatting **
**    Names    **
*****************
rename namematch nm

** Need to check for duplicate death registrations
** First split full name into first, middle and last names
** Also - code to split full name into 2 variables fname and lname - else can't merge! 
split pname, parse(", "" ") gen(name)
order record_id pname name*
sort record_id

** Use Stata browse to view results as changes are made
** (1) sort cases that contain only a first name and a last name
count if name7=="" & name6=="" & name5=="" & name4=="" & name3=="" & name2=="" //0
count if name6=="" & name5=="" & name4=="" & name3=="" & name2=="" //0
count if name5=="" & name4=="" & name3=="" & name2=="" //0
count if name5=="" & name4=="" & name3=="" //2283
count if name7!="" //3
count if name6!="" //4
count if name5!="" //6
count if name4!="" //81
count if name3!="" //853
count if name2!="" //3136
count if name1!="" //3136

** (2) sort name8 + name7 fields
replace name1=name1+" "+name5+" "+name6+" "+name7+" "+name8 if record_id==35038|record_id==35120
replace name2=name2+" "+name3 if record_id==35038|record_id==35120
replace name3=name4 if record_id==35038|record_id==35120
replace name1=name1+" "+name4+" "+name5+" "+name6+" "+name7 if record_id==37127
replace name4="" if record_id==35038|record_id==35120|record_id==37127
replace name5="" if record_id==35038|record_id==35120|record_id==37127
replace name6="" if record_id==35038|record_id==35120|record_id==37127
drop name7 name8

** (2) sort name6 field
replace name1=name1+" "+name3+" "+name4+" "+name5+" "+name6 if record_id==37158
replace name3=name2 if record_id==37158
replace name2="" if record_id==37158
replace name1=name1+" "+name2+" "+name3 if record_id==37199
replace name2=name4 if record_id==37199
replace name2=name2+" "+name3+"."+name4 if record_id==36382
replace name3=name5 if record_id==37199|record_id==36382
replace name4="" if record_id==37158|record_id==37199|record_id==36382
drop name5 name6

** (4) sort cases with name 'baby' or 'b/o' in name1 variable
count if (regexm(name1,"BABY")|regexm(name1,"B/O")|regexm(name1,"MALE")|regexm(name1,"FEMALE")) //9
//gen tempvarn=1 if (regexm(name1,"BABY")|regexm(name1,"B/O")|regexm(name1,"MALE")|regexm(name1,"FEMALE"))
count if name1=="BABY" //4
gen tempvarn=1 if name1=="BABY"
//list record_id pname name1 name2 name3 name4 name5 if tempvarn==1
//list record_id pname name6 name7 if tempvarn==1
//replace tempvarn=. if record_id==31995|record_id==32479
replace name1=name1+" "+name2+" "+name3 if tempvarn==1 //4 changes
replace name2="" if tempvarn==1 //4 changes
replace name3=name4 if tempvarn==1 //4 changes
replace name4="" if tempvarn==1 //4 changes
count if (regexm(name2,"BABY")|regexm(name2,"B/O")|regexm(name2,"MALE")|regexm(name2,"FEMALE")) //0
replace tempvarn=1 if (regexm(name2,"BABY")|regexm(name2,"B/O")|regexm(name2,"MALE")|regexm(name2,"FEMALE"))
replace tempvarn=. if tempvarn!=. //4 changes
count if (regexm(name3,"BABY")|regexm(name3,"B/O")|regexm(name3,"MALE")|regexm(name3,"FEMALE")) //0
count if (regexm(name4,"BABY")|regexm(name4,"B/O")|regexm(name4,"MALE")|regexm(name4,"FEMALE")) //0

** (5)
** Names containing 'ST' are being interpreted as 'ST'=name1/fname so correct
count if name1=="ST" | name1=="ST." //5
replace tempvarn=1 if name1=="ST" | name1=="ST." //5 changes
//list record_id pname name1 name2 name5 if tempvarn==2
replace name1 = subinstr(name1, ".", "",1) if tempvarn==1 //1 change
replace name1=name1+"."+""+name2 if tempvarn==1 //5 changes
replace name2="" if tempvarn==1 //5 changes
replace tempvarn=. if tempvarn!=. //5 changes
** Names containing 'ST' are being interpreted as 'ST'=name2/fname so correct
count if name2=="ST" | name2=="ST." //21
replace tempvarn=1 if name2=="ST" | name2=="ST." //21 changes
replace name3=name2+"."+name3 if tempvarn==1 & name4=="" //10 changes
replace name2="" if tempvarn==1 & name4=="" //10 changes
replace tempvarn=. if tempvarn==1 & name4=="" //10 changes
replace name2=name2+"."+name3 if tempvarn==1 //11 changes
replace name3=name4 if tempvarn==1 //11 changes
replace name4="" if tempvarn==1 //11 changes
replace tempvarn=. if tempvarn!=. //11 changes
** Names containing 'ST' are being interpreted as 'ST'=name3/fname so correct
count if name3=="ST" | name3=="ST." //2
replace tempvarn=1 if name3=="ST" | name3=="ST."
replace name3=name3+"."+""+name4 if tempvarn==1 //2 changes
replace name4="" if tempvarn==1 //2 changes
count if name4=="ST" | name4=="ST." //0
replace tempvarn=. if tempvarn!=. //2 changes

** (6) sort cases with name in name4 variable
count if name4!="" //58
//list record_id *name* if name4!=""
replace name2=name2+" "+name3 if name4!="" //58 changes
replace name3=name4 if name4!="" //58 changes
replace name4="" if name4!="" //58 changes
drop name4

** (7) sort cases with suffixes
count if (name3!="" & name3!="99") & length(name3)<4 //3 - 0 need correcting
//replace tempvarn=1 if (name3!="" & name3!="99") & length(name3)<4 //4 changes
//list record_id pname fname mname lname if (lname!="" & lname!="99") & length(lname)<3

** (8) sort cases with NO name in name3 variable
count if name3=="" //2283
//list record_id *name* if name3==""
replace tempvarn=1 if name3=="" //2283 changes
replace name3=name2 if tempvarn==1 //2283 changes
replace name2="" if tempvarn==1 //2283 changes
drop tempvarn

** Now rename, check and remove unnecessary variables
count if name1=="" //0
count if name2=="" //2303
count if name3=="" //0
rename name1 fname
rename name2 mname
rename name3 lname
count if fname=="" //0
count if lname=="" //0

** Convert names to lower case and strip possible leading/trailing blanks
replace fname = lower(rtrim(ltrim(itrim(fname)))) //3136 changes
replace mname = lower(rtrim(ltrim(itrim(mname)))) //833 changes
replace lname = lower(rtrim(ltrim(itrim(lname)))) //3136 changes

rename nm namematch

** Populate natregno (string) field with NRNs
gen double natregno = nrn
format natregno %15.0g
tostring natregno ,replace
order record_id pname fname mname lname nrn natregno age namematch

count if length(natregno)==9 //13
count if length(natregno)==8 //0
count if length(natregno)==7 //2
replace natregno="0" + natregno if length(natregno)==9 //13 changes
replace natregno="00" + natregno if length(natregno)==8 //0 changes
replace natregno="000" + natregno if length(natregno)==7 //2 changes
count if natregno=="." //87
replace natregno="" if natregno=="." //87 changes
count if natregno!="" & length(natregno)!=10 //0
count if nrn!=. & natregno=="" //0
count if nrn!=. & natregno=="" //0


** Now generate a new variable which will select out all the potential cancers
gen cancer=.
label define cancer_lab 1 "cancer" 2 "not cancer", modify
label values cancer cancer_lab
label var cancer "cancer diagnoses"
label var record_id "Event identifier for registry deaths"

** searching cod1a for these terms
replace cod1a="99" if cod1a=="999" //0 changes
replace cod1b="99" if cod1b=="999" //0 changes
replace cod1c="99" if cod1c=="999" //0 changes
replace cod1d="99" if cod1d=="999" //0 changes
replace cod2a="99" if cod2a=="999" //0 changes
replace cod2b="99" if cod2b=="999" //0 changes
count if cod1c!="99" //779
count if cod1d!="99" //236
count if cod2a!="99" //1456
count if cod2b!="99" //688
//ssc install unique
//ssc install distinct
** Create variable with combined CODs
gen coddeath=cod1a+" "+cod1b+" "+cod1c+" "+cod1d+" "+cod2a+" "+cod2b
replace coddeath=subinstr(coddeath,"99 ","",.) //2997 changes
replace coddeath=subinstr(coddeath," 99","",.) //2447 changes
** Identify cancer deaths using variable called 'cancer'
replace cancer=1 if regexm(coddeath, "CANCER") & cancer==. //391 changes
replace cancer=1 if regexm(coddeath, "TUMOUR") &  cancer==. //11 changes
replace cancer=1 if regexm(coddeath, "TUMOR") &  cancer==. //7 changes
replace cancer=1 if regexm(coddeath, "MALIGNANT") &  cancer==. //12 changes
replace cancer=1 if regexm(coddeath, "MALIGNANCY") &  cancer==. //22 changes
replace cancer=1 if regexm(coddeath, "NEOPLASM") &  cancer==. //3 changes
replace cancer=1 if regexm(coddeath, "NEOPLAST") &  cancer==. //1 change
replace cancer=1 if regexm(coddeath, "CARCINOMA") &  cancer==. //161 changes
replace cancer=1 if regexm(coddeath, "CARCIMONA") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "CARINOMA") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "MYELOMA") &  cancer==. //32 changes
replace cancer=1 if regexm(coddeath, "LYMPHOMA") &  cancer==. //29 changes
replace cancer=1 if regexm(coddeath, "LYMPHOMIA") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "LYMPHONA") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "SARCOMA") &  cancer==. //11 changes
replace cancer=1 if regexm(coddeath, "TERATOMA") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "LEUKEMIA") &  cancer==. //12 changes
replace cancer=1 if regexm(coddeath, "LEUKAEMIA") &  cancer==. //3 changes
replace cancer=1 if regexm(coddeath, "HEPATOMA") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "CARANOMA PROSTATE") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "MENINGIOMA") &  cancer==. //2 changes
replace cancer=1 if regexm(coddeath, "MYELOSIS") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "MYELOFIBROSIS") &  cancer==. //0 change
replace cancer=1 if regexm(coddeath, "CYTHEMIA") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "CYTOSIS") &  cancer==. //1 change
replace cancer=1 if regexm(coddeath, "BLASTOMA") &  cancer==. //4 changes
replace cancer=1 if regexm(coddeath, "METASTATIC") &  cancer==. //2 changes
replace cancer=1 if regexm(coddeath, "MASS") &  cancer==. //20 changes
replace cancer=1 if regexm(coddeath, "METASTASES") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "METASTASIS") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "REFRACTORY") &  cancer==. //2 changes
replace cancer=1 if regexm(coddeath, "FUNGOIDES") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "HODGKIN") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath, "MELANOMA") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath,"MYELODYS") &  cancer==. //2 changes
replace cancer=1 if regexm(coddeath,"ASTROCYTOMA") &  cancer==. //1 change
replace cancer=1 if regexm(coddeath,"CARCINOME") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath,"MALIGANCY") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath,"MULTIFORME") &  cancer==. //0 changes
replace cancer=1 if regexm(coddeath,"GLIOMA") &  cancer==. //0 changes

** Strip possible leading/trailing blanks in cod1a
replace coddeath = rtrim(ltrim(itrim(coddeath))) //0 changes

tab cancer, missing //2407 missing

sort coddeath record_id
order record_id coddeath natregno

drop dodyear
gen dodyear=year(dod)
tab dodyear cancer,m


** Check that all cancer CODs are eligible
sort coddeath record_id
order record_id coddeath natregno
//list coddeath if cancer==1 & inrange(record_id, 0, 24000)
** 588
//list coddeath if cancer==1 & inrange(record_id, 24001, 27000)
** 778

** Replace deaths that are not cancer according to eligibility SOP:
/*
	(1) After merge with CR5 data then may need to reassign some of below 
		deaths as CR5 data may indicate eligibility while COD may exclude
		(e.g. see record_id==15458)
	(2) use obsid to check for CODs that incomplete in Results window with 
		Data Editor in browse mode-copy and paste record_id below from here
*/

** Check that all CODs that are not cancer for eligibility (easier to do below review in Browse Stata window)
tab dodyear cancer,m
count if cancer==. & inrange(record_id, 0, 23000)
count if cancer==. & inrange(record_id, 23001, 24000)
count if cancer==. & inrange(record_id, 24001, 2000)
//list coddeath if cancer==. & inrange(record_id, 0, 24000)
//list coddeath if cancer==. & inrange(record_id, 24001, 27000)

replace cancer=2 if ///
record_id==34641|record_id==34171|record_id==34342|record_id==35020|record_id==35444| ///
record_id==36218|record_id==34272|record_id==34505|record_id==36871|record_id==34414| ///
record_id==34943|record_id==35581|record_id==35608|record_id==36267|record_id==35352| ///
record_id==34875|record_id==35852|record_id==36332|record_id==34736|record_id==35738| ///
record_id==35659|record_id==35536|record_id==35376|record_id==34393|record_id==35878| ///
record_id==36498|record_id==34401|record_id==35157|record_id==37155|record_id==34935| ///
record_id==36394|record_id==35842|record_id==34378|record_id==37347|record_id==34458| ///
record_id==36980|record_id==34460|record_id==34196|record_id==36390|record_id==36248| ///
record_id==35806|record_id==37263|record_id==35432|record_id==34152
//44 changes

replace cancer=1 if record_id==37188|record_id==36674|record_id==34999|record_id==36305| ///
					record_id==36358|record_id==35196|record_id==34246|record_id==36619
//8 changes

replace cancer=2 if cancer==. //2399 changes

** Spelling corrections from the above list reviews; Also emailed to KG on 11jul2022 to update in multi-year REDCap deathdb
replace coddeath=subinstr(coddeath,"AVARIAN","OVARIAN",.) if record_id==35653
replace coddeath=subinstr(coddeath,"SENOUS","SEROUS",.) if record_id==35576
replace coddeath=subinstr(coddeath,"LEUFAEMIA","LEUKAEMIA",.) if record_id==37188
replace coddeath=subinstr(coddeath,"CACINOMA","CARCINOMA",.) if record_id==36674
replace coddeath=subinstr(coddeath,"HODKINS","HODGKINS",.) if record_id==34999
replace coddeath=subinstr(coddeath,"COID","COVID",.) if record_id==37168
replace coddeath=subinstr(coddeath,"MYOCARDIAL I","MYOCARDIAL INFARCTION",.) if record_id==36466
replace coddeath=subinstr(coddeath,"CARCINOM","CARCINOMA",.) if record_id==36358
replace coddeath=subinstr(coddeath,"ARTERY IS","ARTERY",.) if record_id==36834
replace coddeath=subinstr(coddeath,";","P",.) if record_id==36283
replace coddeath=subinstr(coddeath,"TRSCT","TRACT",.) if record_id==36283
replace coddeath=subinstr(coddeath,"ANERAL","ARTERIAL",.) if record_id==34932
replace coddeath=subinstr(coddeath,"UBDURAL","SUBDURAL",.) if record_id==37137
replace coddeath=subinstr(coddeath,"FOO","FOOT",.) if record_id==36975


** Create cod variable 
gen cod=.
label define cod_lab 1 "Dead of cancer" 2 "Dead of other cause" 3 "Not known" 4 "NA", modify
label values cod cod_lab
label var cod "COD categories"
replace cod=1 if cancer==1 //693 changes
replace cod=2 if cancer==2 //2443 changes
** one unknown causes of death in 2014 data - record_id 12323
replace cod=3 if coddeath=="99"|(regexm(coddeath,"INDETERMINATE")|regexm(coddeath,"UNDETERMINED")|regexm(coddeath,"UNKNOWN CAUSE")|regexm(coddeath,"NO ANATOMICAL CAUSE")) //28 changes
//list record_id coddeath if cod==3
replace cod=1 if record_id==34737


** Change sex to match cancer dataset
tab sex ,m
/*
        Sex |      Freq.     Percent        Cum.
------------+-----------------------------------
       Male |      1,593       50.80       50.80
     Female |      1,539       49.08       99.87
         ND |          4        0.13      100.00
------------+-----------------------------------
      Total |      3,136      100.00
*/
replace sex=2 if sex==99 //4 changes

rename sex sex_old
gen sex=1 if sex_old==2 //1543 changes
replace sex=2 if sex_old==1 //1593 changes
drop sex_old
label define sex_lab 1 "Female" 2 "Male", modify
label values sex sex_lab
label var sex "Sex"
tab sex ,m
/*
        Sex |      Freq.     Percent        Cum.
------------+-----------------------------------
     Female |      1,543       49.20       49.20
       Male |      1,593       50.80      100.00
------------+-----------------------------------
      Total |      3,136      100.00
*/


** Spotting some duplicates so re-check for duplicates (since 2019 Pt.1 death cleaning was done at different time to 2019 Pt.2 these duplicates were missed)
** Delete records in multi-year REDCap database
sort regnum district
quietly by regnum district:  gen dupreg = cond(_N==1,0,_n)
sort regnum district
count if event==1 & dupreg>0  //517 - same reg #s but different pts
sort regnum pname record_id
//list record_id dddoa ddda odda pname regnum district nrn if event==1 & dupreg>0, sepby(regnum)
//list record_id dddoa ddda odda pname regnum district nrn if event==1 & dupreg>0 & inrange(record_id, 26000, 28000)
//list record_id dddoa ddda odda pname regnum district nrn if event==1 & dupreg>0 & inrange(record_id, 28001, 30000)
drop dupreg


sort pname
quietly by pname:  gen dup = cond(_N==1,0,_n)
sort pname
count if event==1 & dup>0  //28 - all different pts with same name
sort pname record_id
//list record_id dddoa ddda odda pname regnum district nrn namematch if event==1 & dup>0, sepby(pname)
/*
replace namematch=1 if record_id==|record_id==|record_id==|record_id==|record_id== ///
					   |record_id==|record_id==|record_id==|record_id==|record_id== ///
					   |record_id==|record_id==|record_id==|record_id==|record_id== ///
					   |record_id==|record_id==|record_id==|record_id== // changes
drop if record_id==|record_id== // deleted
*/
//drop if event==1 & dup>0 & namematch==. // deleted
drop dup

** Create DOB variable to correspond with 2015-2020 death matching dataset
order record_id natregno age
count if natregno==""|natregno=="." //87
gen tempvarn=6 if natregno==""|natregno=="."
gen yr = substr(natregno,1,1) if tempvarn!=6
gen yr1=. if tempvarn!=6
replace yr1 = 20 if yr=="0" & tempvarn!=6
replace yr1 = 19 if yr!="0" & tempvarn!=6
replace yr1 = 99 if natregno=="99" & tempvarn!=6
order record_id natregno nrn age yr yr1
replace yr1=20 if yr1==19 & age<21 //9 changes

tostring yr1 ,replace
gen nrn2=substr(natregno, 1,6)
replace nrn2=yr1+nrn2 if tempvarn!=6

gen natregno2 = substr(nrn2, 1,4) + "/" + substr(nrn2, 5,2) + "/" + substr(nrn2, 7,2) if tempvarn!=6
order record_id natregno nrn age yr yr1 natregno2 nrn2
gen dob=date(natregno2, "YMD")
format dob %dD_m_CY
order record_id natregno dob nrn age yr yr1 natregno2 nrn2
drop yr yr1 natregno2 nrn2


** Remove, relabel certain variables for appending to 2015-2020 death matching dataset
drop tempvarn
rename * dd_*
rename dd_record_id record_id

order record_id dd_pname dd_fname dd_mname dd_lname dd_regnum dd_nrn dd_sex dd_age dd_dod dd_cancer dd_cod1a dd_address dd_parish dd_pod dd_coddeath dd_namematch dd_dddoa dd_ddda dd_odda dd_certtype dd_district dd_agetxt dd_nrnnd dd_mstatus dd_occu dd_durationnum dd_durationtxt dd_onsetnumcod1a dd_onsettxtcod1a dd_cod1b dd_onsetnumcod1b dd_onsettxtcod1b dd_cod1c dd_onsetnumcod1c dd_onsettxtcod1c dd_cod1d dd_onsetnumcod1d dd_onsettxtcod1d dd_cod2a dd_onsetnumcod2a dd_onsettxtcod2a dd_cod2b dd_onsetnumcod2b dd_onsettxtcod2b dd_deathparish dd_regdate dd_certifier dd_certifieraddr dd_cleaned dd_duprec dd_elecmatch dd_cod dd_natregno dd_dob dd_dodyear

** Create dataset for combining 2015-2020 deaths for matching (change variable names AFTER all datasets are combined and BEFORE matching with cancer dataset)
label data "BNR MORTALITY data 2021"
notes _dta :These data prepared from BB national death register & Redcap deathdata database
save "`datapath'\version09\2-working\2021_deaths_for_matching" ,replace
note: TS This dataset can be used for combining 2021 deaths with 2015-2020 deaths into one dataset for matching with cancer data

*****************************
**     Append 2015-2020 
**	Death Matching Dataset **
*****************************
count //3,136; 3142; 3143; 3145
append using "`datapath'\version04\3-output\2015-2020_deaths_for_matching"
count //18,561

** JC 12jul2022: correction found incidentally
replace dd_natregno=subinstr(dd_natregno,"2","7",.) if record_id==22335
replace dd_nrn=dd_nrn+500000000 if record_id==22335
swapval dd_fname dd_lname if record_id==22335
gen pname2=substr(dd_pname,1,7) if record_id==22335
gen pname3=substr(dd_pname,-11,11) if record_id==22335
replace dd_pname=pname3+" "+pname2 if record_id==22335
drop pname2 pname3


drop dd_dodyear
gen dd_dodyear=year(dd_dod)
tab dd_dodyear,m
/*
 dd_dodyear |      Freq.     Percent        Cum.
------------+-----------------------------------
       2015 |      2,482       13.37       13.37
       2016 |      2,488       13.40       26.78
       2017 |      2,530       13.63       40.41
       2018 |      2,527       13.61       54.02
       2019 |      2,786       15.01       69.03
       2020 |      2,606       14.04       83.07
       2021 |      3,142       16.93      100.00
------------+-----------------------------------
      Total |     18,561      100.00
*/

** Create dataset without name changes for matching (see dofile 50)
label data "BNR MORTALITY data 2015-2021"
notes _dta :These data prepared from BB national death register & Redcap deathdata database
save "`datapath'\version09\3-output\2015-2021_deaths_for_matching" ,replace
note: TS This dataset can be used for matching 2015-2021 deaths with incidence data
